FROM python:3.10-slim

WORKDIR /app

# 1) 모든 소스코드 복사
COPY . .

# 2) 필요한 패키지 설치
RUN pip install --no-cache-dir -r requirements.txt

# 3) FastAPI 실행
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
